version: "3.8"
services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: app_user
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    restart: on-failure
    ports:
      - "54320:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

  db-populator:
    build:
      context: .
      dockerfile: db-populator/Dockerfile
    environment:
      DATABASE_URL: postgresql://app_user:password@db:5432/app_db
    restart: on-failure
